### ISSUE TITLE
Cannot install in Ubuntu npm.

### ISSUE THREAD

**Issue by take-cheeze** [creationix/node-leveldb#15]
I used "npm install leveldb" to install it but after the build has succeeded I had the following error:

> Waf: Leaving directory `/home/takeshi/.node_libraries/.npm/leveldb/0.5.5/package/build'
> 'build' finished successfully (1.915s)
> sh: ./node_modules/coffee-script/bin/coffee: not found
> npm ERR! install failed Error: leveldb@0.5.5 postinstall:`./node_modules/coffee-script/bin/coffee -b -c -o lib/ src`
> npm ERR! install failed`sh`failed with 127
> npm ERR! install failed     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/exec.js:25:18)
> npm ERR! install failed     at ChildProcess.emit (events.js:67:17)
> npm ERR! install failed     at ChildProcess.onexit (child_process.js:192:12)
> npm ERR! Error: leveldb@0.5.5 postinstall:`./node_modules/coffee-script/bin/coffee -b -c -o lib/ src`
> npm ERR!`sh` failed with 127
> npm ERR!     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/exec.js:25:18)
> npm ERR!     at ChildProcess.emit (events.js:67:17)
> npm ERR!     at ChildProcess.onexit (child_process.js:192:12)
> npm ERR! 
> npm ERR! Failed at the leveldb@0.5.5 postinstall script.
> npm ERR! This is most likely a problem with the leveldb package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ./node_modules/coffee-script/bin/coffee -b -c -o lib/ src
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls leveldb
> npm ERR! There may be additional logging output above.
> npm not ok

I installed npm, coffee, node with aptitude in Ubuntu. Is there a way to solve this?
(coffee-script is installed with npm too.)

**Comment by take-cheeze** [comment]
Seems not active so closing
